Argument 1 must be of the type integer, string given
Amount is a string coming from the CLI. Must be casted due to type hinting 

Fatal error: Uncaught TypeError: Argument 1 passed to Humus\Amqp\AbstractConsumer::consume() must be of the type integer, string given, called in

```
php ./bin/humus-amqp.php consumer --name command-consumer --amount 100
```